*
* THIS PROGRAM HAS TO BE SAVED AS showPRGs.PRG IN ORDER TO
* BE COMPILED AND RUN BY DBASE IV
*
* 
*
* 



CLOSE ALL

SET BELL OFF
SET TALK OFF

CLEAR

@  3,1 SAY "                  THESE PROGRAMS ARE USED BY TEST_.PRG"
@  4,1 TO 17,79

Y=1
X=15
@  6-Y,1+X SAY "                  TEST_.PRG"
@  8-Y,1+X SAY "                  SHOW0_.PRG"
@ 10-Y,1+X SAY "                  CPX19.PRG"
@ 12-Y,1+X SAY "                  FINDR1_.PRG"
@ 14-Y,1+X SAY "                  CLEAR4TO16.PRG"
@ 16-Y,1+X SAY "                  SHOWPRGs.PRG"